extends: default

ignore: |
  .git/
  .cache/
  .generated/
  .venv/
  roles/*/templates/

rules:
  document-start: disable
  line-length: disable
  truthy:
    allowed-values: ['true', 'false']
    check-keys: false
  comments:
    min-spaces-from-content: 1
  indentation:
    indent-sequences: true
