---
- name: Retrieve op items
  hosts: localhost
  environment:
    OP_CONNECT_HOST: "{{ connect_host }}/v1/vaults"
  collections:
    - onepassword.connect
  roles:
    - op
  tags:
    - op

- name: GPU Playbook
  hosts: "{{ host }}"
  become: true
  become_user: root
  serial: "{{ serial_hosts | default(1) }}"
  roles:
    - gpu
  tags:
    - gpu

- name: Tailscale Playbook
  hosts: "{{ host }}"
  become: true
  become_user: root
  serial: "{{ serial_hosts | default(1) }}"
  roles:
    - tailscale
  tags:
    - tailscale
