---
- name: Tailscale Playbook
  hosts: "{{ host }}"
  become: true
  become_user: root
  serial: "{{ serial_hosts | default(1) }}"
  roles:
    - tailscale
  tags:
    - tailscale

- name: Retrieve op items
  hosts: localhost
  roles:
    - op
  tags:
    - op

- name: Provider Playbook
  hosts: "{{ host }}"
  become: true
  become_user: root
  serial: "{{ serial_hosts | default(1) }}"
  roles:
    - provider
    - cron
  tags:
    - provider
    - cron

- name: GPU Playbook
  hosts: "{{ host }}"
  become: true
  become_user: root
  serial: "{{ serial_hosts | default(1) }}"
  roles:
    - gpu
  tags:
    - gpu

