---
# vars file for tailscale
tailscale_apt_dependencies:
  - gnupg
  - gnupg-agent
  - apt-transport-https
  - python3-apt

tailscale_distro: ubuntu
tailscale_release: stable
tailscale_package: tailscale
tailscale_service: tailscaled
tailscale_statefile_name: ".ocl-tailscale"
tailscale_apt_keyring_path: /usr/share/keyrings/tailscale-archive-keyring.gpg
tailscale_apt_repo: deb [signed-by={{ tailscale_apt_keyring_path }}] https://pkgs.tailscale.com/{{ tailscale_release | lower }}/{{ tailscale_distro | lower }} {{ ansible_distribution_release | lower }} main
tailscale_apt_signkey: https://pkgs.tailscale.com/{{ tailscale_release | lower }}/{{ ansible_distribution | lower }}/{{ ansible_distribution_release | lower }}.noarmor.gpg
