---
# Tasks for deploying the Rook-Ceph operator

- name: Include Rook-Ceph defaults
  include_vars: "../rook-ceph-defaults.yml"

- name: Create Rook-Ceph namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ rook_ceph_namespace }}"

- name: Add Rook release Helm repository
  kubernetes.core.helm_repository:
    name: rook-release
    repo_url: https://charts.rook.io/release
    state: present

- name: Install Rook Ceph Operator Helm chart
  kubernetes.core.helm:
    name: rook-ceph-operator
    chart_ref: rook-release/rook-ceph
    release_namespace: "{{ rook_ceph_namespace }}"
    create_namespace: true
    chart_version: "{{ rook_ceph_version }}"
    wait: yes
    wait_timeout: 600s

- name: Wait for Rook-Ceph operator to be ready
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: rook-ceph-operator
    namespace: "{{ rook_ceph_namespace }}"
  register: operator
  until: 
    - operator.resources is defined
    - operator.resources | length > 0
    - operator.resources[0].status is defined 
    - operator.resources[0].status.readyReplicas is defined
    - operator.resources[0].status.readyReplicas > 0
  retries: 30
  delay: 10
