---
- name: Sign in to op account
  ansible.builtin.command:
    argv:
      - op
      - signin
      - --account
      - "{{ opconnect_account_name }}"
  changed_when: false

- name: Get provider vault metadata
  ansible.builtin.command:
    argv:
      - op
      - vault
      - get
      - "{{ vault_name }}"
      - --format=json
  register: vault_id_result
  changed_when: false

- name: Store the vault ID in a variable
  ansible.builtin.set_fact:
    vault_uuid: "{{ (vault_id_result.stdout | from_json).id }}"

- name: Read provider credential fields
  ansible.builtin.command:
    argv:
      - op
      - read
      - "op://{{ vault_name }}/{{ provider_name }}/{{ item }}"
  register: b64_key_output
  changed_when: false
  loop:
    - "{{ provider_b64_key_field }}"
    - "{{ provider_b64_sec_field }}"
  no_log: true

- name: Store outputs in separate variables
  ansible.builtin.set_fact:
    provider_b64_key: "{{ b64_key_output.results[0].stdout | default('') }}"
    provider_b64_keysecret: "{{ b64_key_output.results[1].stdout | default('') }}"
  no_log: true

- name: Require both provider credential fields
  ansible.builtin.assert:
    that:
      - provider_b64_key | length > 0
      - provider_b64_keysecret | length > 0
    fail_msg: The provider key or key secret was empty in 1Password.
  no_log: true
