---
- name: Prerequisites
  ansible.builtin.import_tasks: prereqs.yml
  tags:
  - prereqs

- name: Initialize the playbook
  ansible.builtin.import_tasks: init.yml
  tags:
  - init

- name: Fetch provider keys
  ansible.builtin.import_tasks: fetch.yml
  tags:
  - fetch
