---
- name: Check for required binaries
  ansible.builtin.shell: "command -v op"
  register: op_binary_check
  changed_when: false
  ignore_errors: true
  check_mode: no

- name: Set facts about missing binaries
  ansible.builtin.set_fact:
    missing_binaries: "{{ ['op'] if op_binary_check.rc != 0 else [] }}"

- name: Display missing binaries
  ansible.builtin.debug:
    msg: "Missing required binaries: {{ missing_binaries | join(', ') }}"
  when: missing_binaries | length > 0

- name: Conditional failure based on missing binaries
  ansible.builtin.fail:
    msg: "Required binaries: {{ missing_binaries | join(', ') }} are missing on {{ ansible_distribution }}. Please install them before continuing."
  when: missing_binaries | length > 0
