---
- name: Disable snapd services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  loop:
    - snapd.service
    - snapd.socket
    - snapd.seeded.service
  failed_when: false

- name: Remove snap packages if they exist
  ansible.builtin.command: snap remove {{ item }}
  loop:
    - lxd
    - core20
    - snapd
  failed_when: false

- name: Purge snapd package
  ansible.builtin.apt:
    name: snapd
    state: absent
    purge: yes
    autoremove: yes

- name: Remove snapd directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/cache/snapd
    - /root/snap        
