---
- name: Set internal_ip for all nodes
  ansible.builtin.set_fact:
    internal_ip: "{{ ansible_host }}"

- name: import K3s installation tasks
  ansible.builtin.import_tasks: prechecks.yml
  when: inventory_hostname in groups['kube_control_plane']

- name: import K3s installation tasks
  ansible.builtin.import_tasks: k3s-master.yml
  when: inventory_hostname in groups['kube_control_plane']

- name: import Calico installation tasks
  ansible.builtin.import_tasks: calico.yml
  when: inventory_hostname == groups['kube_control_plane'][0]

- name: import K3s Worker tasks
  ansible.builtin.import_tasks: k3s-worker.yml
  when: not is_control_plane
