---
- name: import K3s installation tasks
  ansible.builtin.import_tasks: prechecks.yml
  when: inventory_hostname in groups['control_plane']

- name: import K3s installation tasks
  ansible.builtin.import_tasks: k3s-master.yml
  when: inventory_hostname in groups['control_plane']

- name: import Calico installation tasks
  ansible.builtin.import_tasks: calico.yml
  when: inventory_hostname in groups['control_plane'][0]

- name: import K3s Worker tasks
  ansible.builtin.import_tasks: k3s-worker.yml
  when: inventory_hostname in groups['workers']
