---
- name: Run K3s control-plane prechecks
  ansible.builtin.import_tasks: prechecks.yml
  when: is_control_plane | bool

- name: Install K3s control plane
  ansible.builtin.import_tasks: k3s-master.yml
  when: is_control_plane | bool

- name: Install Calico from the first control-plane node
  ansible.builtin.import_tasks: calico.yml
  when: inventory_hostname == groups['kube_control_plane'][0]

- name: Install K3s worker
  ansible.builtin.import_tasks: k3s-worker.yml
  when: not (is_control_plane | bool)
