- name: Check if specific IP exists on this host
  ansible.builtin.set_fact:
    ip_exists: "{{ internal_ip in ansible_facts['all_ipv4_addresses'] }}"

- name: Fail if the specific IP is not found
  ansible.builtin.fail:
    msg: "The required IP address {{ internal_ip }} was not found on this host. Please enter the right Internal IP"
  when: not ip_exists
