---
- name: Skipping Authentication
  ansible.builtin.debug:
    msg: You have set 'tailscale_up_skip', so this node will not authenticate to your Tailscale network.
  when: tailscale_up_skip

- name: Tailscale Auth Key Required
  ansible.builtin.fail:
    msg: >
      You must include a Node Authorization auth key.
      Set a `tailscale_authkey` variable.
      You can create this key from: https://login.tailscale.com/admin/settings/keys.
  when:
    - not tailscale_authkey
    - not tailscale_up_skip

- name: Apt Dependencies
  ansible.builtin.apt:
    name: "{{ tailscale_apt_dependencies }}"
    cache_valid_time: 3600
    state: present
