---
- name: Copy provider maintenance scripts to /usr/local/bin
  ansible.builtin.copy:
    src: akash-force-new-replicasets.sh
    dest: /usr/local/bin/akash-force-new-replicasets.sh
    mode: '0755'
    owner: root
    group: root

- name: Create provider maintenance cron jobs
  ansible.builtin.copy:
    dest: "/etc/cron.d/{{ item.filename }}"
    content: "{{ item.content }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - filename: akash-delete-failed-pods
      content: |
        PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
        SHELL=/bin/bash
        KUBECONFIG=/root/.kube/config
        */10 * * * * root kubectl delete pods -A -l akash.network=true --field-selector status.phase=Failed
    - filename: akash-force-new-replicasets
      content: |
        PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
        SHELL=/bin/bash
        KUBECONFIG=/root/.kube/config
        */5 * * * * root /usr/local/bin/akash-force-new-replicasets.sh
