---
- name: Check if provider vars file exists
  become: false
  ansible.builtin.stat:
    path: /tmp/provider_vars_temp.txt
  delegate_to: localhost
  register: provider_vars_file

- name: Check if node has control-plane label
  ansible.builtin.shell: kubectl get node {{ inventory_hostname }} --no-headers -o custom-columns=LABELS:.metadata.labels | grep -q 'node-role.kubernetes.io/control-plane\|node-role.kubernetes.io/master'
  register: control_plane_check
  failed_when: false
  changed_when: false

- name: Fail if not a control plane node
  ansible.builtin.fail:
    msg: "This task can only be run on a Kubernetes control plane node"
  when: control_plane_check.rc != 0

- name: Check if provider keys are passed as variables
  ansible.builtin.set_fact:
    provider_keys_passed: "{{ provider_b64_key is defined and provider_b64_keysecret is defined }}"

- name: Fail playbook if provider vars file does not exist
  ansible.builtin.fail:
    msg: "The provider_b64_key and provider_b64_keysecret were not found. Please run the op role first or pass the provider_b64_key & provider_b64_keysecret via extra vars or host vars"
  when: not provider_vars_file.stat.exists and not provider_keys_passed | default(false)

- name: Read provider variables from file
  become: false
  ansible.builtin.slurp:
    src: "/tmp/provider_vars_temp.txt"
  when: not provider_keys_passed
  delegate_to: localhost
  register: provider_vars_file

- name: Set facts from file content
  ansible.builtin.set_fact:
    provider_b64_key: "{{ (provider_vars_file['content'] | b64decode).split('\n')[0].split(': ')[1] }}"
    provider_b64_keysecret: "{{ (provider_vars_file['content'] | b64decode).split('\n')[1].split(': ')[1] }}"
  when: not provider_keys_passed
  no_log: true

- name: Debug provider keys
  ansible.builtin.debug:
    msg:
      - "provider_b64_key: {{ provider_b64_key | default('Not defined') }}"
      - "provider_b64_keysecret: {{ provider_b64_keysecret | default('Not defined') }}"
  when: not provider_keys_passed

- name: Clean up temporary YAML file
  become: false
  ansible.builtin.file:
    path: "/tmp/provider_vars_temp.txt"
    state: absent
  delegate_to: localhost
