---
- name: Check if provider vars file exists
  stat:
    path: /tmp/provider_vars_temp.txt
  delegate_to: localhost
  register: provider_vars_file

- name: Fail playbook if provider vars file does not exist
  fail:
    msg: "The provider_b64_key and provider_b64_keysecret were not found. Please run the op role first or pass the provider_b64_key & provider_b64_keysecret via extra vars"
  when: not provider_vars_file.stat.exists

- name: Read provider variables from file
  ansible.builtin.slurp:
    src: "/tmp/provider_vars_temp.txt"
  delegate_to: localhost
  register: provider_vars_file

- name: Set facts from file content
  ansible.builtin.set_fact:
    provider_b64_key: "{{ (provider_vars_file['content'] | b64decode).split('\n')[0].split(': ')[1] }}"
    provider_b64_keysecret: "{{ (provider_vars_file['content'] | b64decode).split('\n')[1].split(': ')[1] }}"
  no_log: true

- name: Debug provider keys
  ansible.builtin.debug:
    msg:
      - "provider_b64_key: {{ provider_b64_key | default('Not defined') }}"
      - "provider_b64_keysecret: {{ provider_b64_keysecret | default('Not defined') }}"

- name: Clean up temporary YAML file
  ansible.builtin.file:
    path: "/tmp/provider_vars_temp.yml"
    state: absent
