---
- name: Remove Akash Helm repository if it exists
  command: helm repo remove akash
  register: remove_result
  failed_when: >
    remove_result.rc != 0 and 
    "Error: repository name (akash) not found" not in remove_result.stderr and
    "Error: no repositories configured" not in remove_result.stderr
  changed_when: remove_result.rc == 0

- name: Add required Helm repositories
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
    state: present
  loop:
    - { name: "akash", url: "https://akash-network.github.io/helm-charts" }
    - { name: "ingress-nginx", url: "https://kubernetes.github.io/ingress-nginx" }

- name: Update Helm repositories
  command: helm repo update
  register: helm_update
  changed_when: "'Update Complete' in helm_update.stdout"
