---
- name: Create sysctl configuration file for Akash
  ansible.builtin.copy:
    dest: /etc/sysctl.d/90-akash.conf
    content: |
      # Common: tackle "failed to create fsnotify watcher: too many open files"
      fs.inotify.max_user_instances = 512
      fs.inotify.max_user_watches = 1048576

      # Custom: increase memory mapped files limit to allow Solana node
      # https://docs.solana.com/running-validator/validator-start
      vm.max_map_count = 1000000

- name: Apply sysctl parameters
  ansible.builtin.command: sysctl -p /etc/sysctl.d/90-akash.conf

- name: Remove Akash Helm repository if it exists
  ansible.builtin.command: helm repo remove akash
  register: remove_result
  failed_when: >
    remove_result.rc != 0 and 
    "Error: repository name (akash) not found" not in remove_result.stderr and
    "Error: no repositories configured" not in remove_result.stderr
  changed_when: remove_result.rc == 0

- name: Add required Helm repositories
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
    state: present
  loop:
    - { name: "akash", url: "https://akash-network.github.io/helm-charts" }
    - { name: "ingress-nginx", url: "https://kubernetes.github.io/ingress-nginx" }

- name: Update Helm repositories
  ansible.builtin.command: helm repo update
  register: helm_update
  changed_when: "'Update Complete' in helm_update.stdout"
