---
# tasks file for gpu
- name: Check if node has NVIDIA GPU
  ansible.builtin.shell: lspci | grep -i nvidia
  register: gpu_check
  changed_when: false
  failed_when: false

- name: Set fact for GPU presence
  ansible.builtin.set_fact:
    has_gpu: "{{ gpu_check.rc == 0 }}"

- name: Skip GPU tasks if no GPU is present
  ansible.builtin.debug:
    msg: "No NVIDIA GPU detected on this node. Skipping GPU tasks."
  when: not has_gpu

- name: Include GPU tasks only if GPU is present
  ansible.builtin.include_tasks: apt_update.yml
  when: has_gpu

- name: Include NVIDIA update tasks only if GPU is present
  ansible.builtin.include_tasks: nvidia_update.yml
  when: has_gpu

- name: Include container toolkit tasks only if GPU is present
  ansible.builtin.include_tasks: nvidia_ctoolkit.yml
  when: has_gpu

- name: Include NVIDIA device plugin tasks only if GPU is present
  ansible.builtin.include_tasks: nvdp.yml
  when: has_gpu


