---
# tasks file for gpu
- name: Check if node has NVIDIA GPU
  ansible.builtin.shell: lspci | grep -i nvidia
  register: gpu_check
  changed_when: false
  failed_when: false

- name: Set fact for GPU presence
  ansible.builtin.set_fact:
    has_gpu: "{{ gpu_check.rc == 0 }}"

- name: Skip GPU tasks if no GPU is present
  ansible.builtin.debug:
    msg: "No NVIDIA GPU detected on this node. Skipping GPU tasks."
  when: not has_gpu

- name: Check current Helm version (if any)
  ansible.builtin.command: helm version --short
  register: helm_version
  failed_when: false

- name: Download Helm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'

- name: Run Helm install script for v3.17.3
  environment:
    HELM_INSTALL_VERSION: "v3.17.3"
  ansible.builtin.command: /tmp/get_helm.sh
  when: helm_version.stdout is not defined or 'v3.17.3' not in helm_version.stdout

- name: Include GPU tasks only if GPU is present
  ansible.builtin.include_tasks: apt_update.yml
  when: has_gpu

- name: Include NVIDIA update tasks only if GPU is present
  ansible.builtin.include_tasks: nvidia_update.yml
  when: has_gpu

- name: Include container toolkit tasks only if GPU is present
  ansible.builtin.include_tasks: nvidia_ctoolkit.yml
  when: has_gpu

- name: Include NVIDIA device plugin tasks only if GPU is present
  ansible.builtin.include_tasks: nvdp.yml
  when: has_gpu


