---
# tasks file for gpu
- name:  apt update
  ansible.builtin.import_tasks: apt_update.yml
 
- name: nvidia update
  ansible.builtin.import_tasks: nvidia_update.yml

- name: Install the container toolkit
  ansible.builtin.import_tasks: nvidia_ctoolkit.yml

- name: Apply the nvidia runtime and nvidia-device-plugin
  ansible.builtin.import_tasks: nvdp.yml

